volumes:
  db_data:
  redis_data:

services:
  db:
    image: postgres:latest
    container_name: local_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cloudedinsights
      POSTGRES_PASSWORD: cloudedinsights
      POSTGRES_DB: tsh_db
    volumes:
      - db_data:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  main_service:
    build:
      context: ./main_service
      dockerfile: Dockerfile
    container_name: main_service
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgresql://cloudedinsights:cloudedinsights@db:5432/tsh_db
      TIMEZONE: Asia/Singapore
      REDIS_URL: redis:6379
      REDIS_TOPIC: trigger-training-forecast
    depends_on:
      - db
      - redis

  forecast_service:
    build:
      context: ./forecast_service
      dockerfile: Dockerfile
    container_name: forecast_service
    ports:
      - 5011:5011
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgresql://cloudedinsights:cloudedinsights@db:5432/tsh_db
      REDIS_URL: redis:6379
      REDIS_TOPIC: trigger-training-forecast
      WHATSAPP_PHONE_ID: ${WHATSAPP_PHONE_ID}
      WHATSAPP_ACCESS_TOKEN: ${WHATSAPP_ACCESS_TOKEN}
      SENDER_EMAIL: ${SENDER_EMAIL}
      SENDER_PASSWORD: ${SENDER_PASSWORD}
    depends_on:
      - db
      - redis
