volumes:
  db_data:
  redis_data:
  ollama_data:

services:
  db:
    image: postgres:latest
    container_name: local_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cloudedinsights
      POSTGRES_PASSWORD: cloudedinsights
      POSTGRES_DB: tsh_db
    volumes:
      - db_data:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  
  # After creating container run: docker exec -it ollama ollama pull phi3/gemma:2b/tinyllama
  # phi3 -> 3.8GB, gemma:2b -> 1.4GB, tinyllama -> 637MB
  # Only need to run once in the cli, then subsequently can just run docker build -up since the model is stored in volumes
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_ORIGINS=*
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  main_service:
    build:
      context: ./main_service
      dockerfile: Dockerfile
    container_name: main_service
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgresql://cloudedinsights:cloudedinsights@db:5432/tsh_db
      TIMEZONE: Asia/Singapore
      REDIS_URL: redis:6379
      REDIS_TOPIC: trigger-training-forecast
    depends_on:
      - db
      - redis

  forecast_service:
    build:
      context: ./forecast_service
      dockerfile: Dockerfile
    container_name: forecast_service
    ports:
      - 5011:5011
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgresql://cloudedinsights:cloudedinsights@db:5432/tsh_db
      REDIS_URL: redis:6379
      REDIS_TOPIC: trigger-training-forecast
    depends_on:
      - db
      - redis
